sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: /hand/camera/pointcloud/filtered
  max_range: 5.0
  max_update_rate: 10.0
  padding_offset: 0.1
  padding_scale: 1.0
  point_cloud_topic: /hand/camera/pointcloud/raw
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater